version: 13
jobs:
  - name: Build (Linux x64)
    steps:
      - !CheckoutStep
        name: checkout
        cloneCredential: !DefaultCredential {}
        withLfs: false
        withSubmodules: false
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !CommandStep
        name: build
        runInContainer: true
        image: ubuntu:24.04
        commands:
          - set -eu
          - apt-get update
          - DEBIAN_FRONTEND=noninteractive apt-get install -y curl git ca-certificates build-essential pkg-config libssl-dev libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
          - curl -fsSL https://deb.nodesource.com/setup_20.x -o /tmp/nodesource_setup_20.sh
          - bash /tmp/nodesource_setup_20.sh
          - DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs
          - corepack enable || true
          - npm ci || npm install
          - curl -fsSL https://sh.rustup.rs | sh -s -- -y --profile minimal
          - . "$HOME/.cargo/env"
          - npm run tauri build
        useTTY: false
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !PublishArtifactStep
        name: publish
        artifacts: src-tauri/target/release/bundle/**
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
    triggers:
      - !BranchUpdateTrigger
        branches: main
    retryCondition: never
    maxRetries: 3
    retryDelay: 30
    timeout: 7200
  - name: Build (Raspberry Pi OS 64-bit ARM64)
    steps:
      - !CheckoutStep
        name: checkout
        cloneCredential: !DefaultCredential {}
        withLfs: false
        withSubmodules: false
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !CommandStep
        name: build
        runInContainer: true
        image: ubuntu:24.04
        commands:
          - set -eu
          - sed -i 's/^Types: deb$/Types: deb\nArchitectures: amd64/' /etc/apt/sources.list.d/ubuntu.sources
          - |
            cat <<EOF > /etc/apt/sources.list.d/arm64.sources
            Types: deb
            URIs: http://ports.ubuntu.com/ubuntu-ports/
            Suites: noble noble-updates noble-security
            Components: main restricted universe multiverse
            Architectures: arm64
            EOF
          - apt-get update
          - DEBIAN_FRONTEND=noninteractive apt-get install -y curl git ca-certificates build-essential pkg-config
          - dpkg --add-architecture arm64
          - apt-get update
          - DEBIAN_FRONTEND=noninteractive apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          - DEBIAN_FRONTEND=noninteractive apt-get install -y libwebkit2gtk-4.1-dev:arm64 libgtk-3-dev:arm64 libayatana-appindicator3-dev:arm64 librsvg2-dev:arm64 libssl-dev:arm64
          - curl -fsSL https://deb.nodesource.com/setup_20.x -o /tmp/nodesource_setup_20.sh
          - bash /tmp/nodesource_setup_20.sh
          - DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs
          - corepack enable || true
          - npm ci || npm install
          - curl -fsSL https://sh.rustup.rs | sh -s -- -y --profile minimal
          - . "$HOME/.cargo/env"
          - rustup target add aarch64-unknown-linux-gnu
          - export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          - export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
          - export PKG_CONFIG_ALLOW_CROSS=1
          - npm run tauri build -- --target aarch64-unknown-linux-gnu
        useTTY: false
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !PublishArtifactStep
        name: publish
        artifacts: src-tauri/target/aarch64-unknown-linux-gnu/release/bundle/**
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
    triggers:
      - !BranchUpdateTrigger
        branches: main
    retryCondition: never
    maxRetries: 3
    retryDelay: 30
    timeout: 10800
