version: 25
jobs:
  - name: Build for Raspberry Pi (ARM64)
    steps:
      - !CheckoutStep
        name: Checkout Code
      - !CommandStep
        name: Cross Compile
        image: debian:bookworm
        runInContainer: true
        interpreter: !DefaultInterpreter
          commands:
          - |
            set -e
            echo ">>> Initialize Environment..."
            
            # 1. Install Basic Tools
            apt-get update
            apt-get install -y curl wget git build-essential pkg-config libssl-dev
            
            # 2. Setup Multiarch for ARM64 (Target Architecture)
            dpkg --add-architecture arm64
            apt-get update
            
            # 3. Install Cross-Compiler and Target Libraries
            apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
            apt-get install -y libwebkit2gtk-4.1-dev:arm64 libgtk-3-dev:arm64 libayatana-appindicator3-dev:arm64 librsvg2-dev:arm64 libssl-dev:arm64
            
            # 4. Install Node.js (v20)
            curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
            apt-get install -y nodejs
            
            # 5. Install Rust and Add ARM64 Target
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -j -y
            source "$HOME/.cargo/env"
            rustup target add aarch64-unknown-linux-gnu
            
            # 6. Configure Environment for Cross-Compilation
            export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
            export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
            export PKG_CONFIG_ALLOW_CROSS=1
            
            # 7. Build Project
            echo ">>> Starting Build..."
            npm install
            npm run tauri build -- --target aarch64-unknown-linux-gnu
            
      - !PublishArtifactStep
        name: Publish Deb
        artifacts: src-tauri/target/aarch64-unknown-linux-gnu/release/bundle/deb/*.deb
        
      - !PublishArtifactStep
        name: Publish AppImage
        artifacts: src-tauri/target/aarch64-unknown-linux-gnu/release/bundle/appimage/*.AppImage
            
    triggers:
      - !BranchUpdateTrigger
        branches: main
