version: 13
jobs:
  - name: Build (Linux x64)
    steps:
      - !CheckoutStep
        name: checkout
        cloneCredential: !DefaultCredential {}
        withLfs: false
        withSubmodules: false
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !CommandStep
        name: build
        runInContainer: true
        image: ubuntu:24.04
        commands:
          - set -eu
          - apt-get update
          - DEBIAN_FRONTEND=noninteractive apt-get install -y curl git ca-certificates build-essential pkg-config libssl-dev libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
          - curl -fsSL https://deb.nodesource.com/setup_20.x -o /tmp/nodesource_setup_20.sh
          - bash /tmp/nodesource_setup_20.sh
          - DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs
          - corepack enable || true
          - npm ci || npm install
          - curl -fsSL https://sh.rustup.rs | sh -s -- -y --profile minimal
          - . "$HOME/.cargo/env"
          - npm run tauri build
        useTTY: false
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !PublishArtifactStep
        name: publish
        artifacts: src-tauri/target/release/bundle/**
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
    triggers:
      - !BranchUpdateTrigger
        branches: main
    retryCondition: never
    maxRetries: 3
    retryDelay: 30
    timeout: 7200
  - name: Build (Raspberry Pi OS ARM64 Native)
    steps:
      - !CheckoutStep
        name: checkout
        cloneCredential: !DefaultCredential {}
        withLfs: false
        withSubmodules: false
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !CommandStep
        name: build
        runInContainer: true
        image: ubuntu:24.04
        commands:
          - set -eu
          - arch=$(uname -m)
          - 'if [ "$arch" != "aarch64" ] && [ "$arch" != "arm64" ]; then echo "This job must run on Raspberry Pi ARM64 executor (aarch64/arm64), current: $arch"; exit 1; fi'
          - apt-get update
          - DEBIAN_FRONTEND=noninteractive apt-get install -y curl git ca-certificates build-essential pkg-config libssl-dev libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
          - curl -fsSL https://deb.nodesource.com/setup_20.x -o /tmp/nodesource_setup_20.sh
          - bash /tmp/nodesource_setup_20.sh
          - DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs
          - corepack enable || true
          - npm ci || npm install
          - curl -fsSL https://sh.rustup.rs | sh -s -- -y --profile minimal
          - . "$HOME/.cargo/env"
          - npm run tauri build
        useTTY: false
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
      - !PublishArtifactStep
        name: publish
        artifacts: src-tauri/target/release/bundle/**
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
    triggers:
      - !BranchUpdateTrigger
        branches: main
    retryCondition: never
    maxRetries: 3
    retryDelay: 30
    timeout: 10800
